
App.controller('SelectController', ['$scope', 'PoeService', function($scope) {



    $scope.modSelect = [
        "-- --",
        "# Life Regenerated per second",
        "#% additional Block Chance",
        "#% additional Block Chance while Dual Wielding",
        "#% additional Chance to Block Spells while Dual Wielding",
        "#% additional Chance to Block Spells with Shields",
        "#% additional Chance to Block Spells with Staves",
        "#% additional Chance to Block with Shields",
        "#% additional Chance to Block with Staves",
        "#% additional Elemental Resistances during Flask effect",
        "#% chance to Freeze",
        "#% chance to gain a Flask Charge when you deal a Critical Strike",
        "#% chance to Ignite",
        "#% chance to Knock Enemies Back on hit",
        "#% chance to Shock",
        "#% faster start of Energy Shield Recharge",
        "#% increased Accuracy Rating",
        "#% increased Area Damage",
        "#% increased Armour",
        "#% increased Armour and Energy Shield",
        "#% increased Armour and Evasion",
        "#% increased Armour during Flask effect",
        "#% increased Armour, Evasion and Energy Shield",
        "#% increased Attack and Cast Speed",
        "#% increased Attack Speed",
        "#% increased Attack Speed while Dual Wielding",
        "#% increased Attack Speed while holding a Shield",
        "#% increased Attack Speed with Axes",
        "#% increased Attack Speed with Bows",
        "#% increased Attack Speed with Claws",
        "#% increased Attack Speed with Daggers",
        "#% increased Attack Speed with Maces",
        "#% increased Attack Speed with One Handed Melee Weapons",
        "#% increased Attack Speed with Staves",
        "#% increased Attack Speed with Swords",
        "#% increased Attack Speed with Two Handed Melee Weapons",
        "#% increased Attack Speed with Wands",
        "#% increased Cast Speed",
        "#% increased Cast Speed while Dual Wielding",
        "#% increased Cast Speed while holding a Shield",
        "#% increased Cast Speed while wielding a Staff",
        "#% increased Cast Speed with Cold Skills",
        "#% increased Cast Speed with Fire Skills",
        "#% increased Cast Speed with Lightning Skills",
        "#% increased Chaos Damage",
        "#% increased Charge Recovery",
        "#% increased Cold Damage",
        "#% increased Critical Strike Chance",
        "#% increased Critical Strike Chance for Spells",
        "#% increased Critical Strike Chance with Cold Skills",
        "#% increased Critical Strike Chance with Elemental Skills",
        "#% increased Critical Strike Chance with Fire Skills",
        "#% increased Critical Strike Chance with Lightning Skills",
        "#% increased Critical Strike Chance with One Handed Melee Weapons",
        "#% increased Critical Strike Chance with Two Handed Melee Weapons",
        "#% increased Damage",
        "#% increased Damage over Time",
        "#% increased Elemental Damage with Weapons",
        "#% increased Energy Shield",
        "#% increased Energy Shield Recharge Rate",
        "#% increased Evasion and Energy Shield",
        "#% increased Evasion Rating",
        "#% increased Evasion Rating during Flask effect",
        "#% increased Fire Damage",
        "#% increased Flask Charges gained",
        "#% increased Flask effect duration",
        "#% increased Flask Life Recovery rate",
        "#% increased Flask Mana Recovery rate",
        "#% increased Freeze Duration on Enemies",
        "#% increased Global Critical Strike Chance",
        "#% increased Ignite Duration on Enemies",
        "#% increased Life Leeched per second",
        "#% increased Life Recovered",
        "#% increased Light Radius",
        "#% increased Lightning Damage",
        "#% increased Mana Regeneration Rate",
        "#% increased maximum Energy Shield",
        "#% increased maximum Life",
        "#% increased maximum Mana",
        "#% increased Melee Critical Strike Chance",
        "#% increased Melee Damage",
        "#% increased Melee Physical Damage while holding a Shield",
        "#% increased Mine Damage",
        "#% increased Mine Laying Speed",
        "#% increased Movement Speed",
        "#% increased Movement Speed during Flask effect",
        "#% increased Physical Damage",
        "#% increased Physical Damage with Axes",
        "#% increased Physical Damage with Bows",
        "#% increased Physical Damage with Claws",
        "#% increased Physical Damage with Daggers",
        "#% increased Physical Damage with Maces",
        "#% increased Physical Damage with One Handed Melee Weapons",
        "#% increased Physical Damage with Staves",
        "#% increased Physical Damage with Swords",
        "#% increased Physical Damage with Two Handed Melee Weapons",
        "#% increased Physical Damage with Wands",
        "#% increased Physical Weapon Damage while Dual Wielding",
        "#% increased Projectile Damage",
        "#% increased Projectile Speed",
        "#% increased Quantity of Items found",
        "#% increased Rarity of Fish Caught",
        "#% increased Rarity of Items found",
        "#% increased Recovery Speed",
        "#% increased Shock Duration on Enemies",
        "#% increased Spell Damage",
        "#% increased Spell Damage while Dual Wielding",
        "#% increased Spell Damage while holding a Shield",
        "#% increased Spell Damage while wielding a Staff",
        "#% increased Stun Duration on Enemies",
        "#% increased Stun Recovery",
        "#% increased Stun Recovery during Flask effect",
        "#% increased Stun Recovery during flask effect",
        "#% increased Totem Damage",
        "#% increased Totem Life",
        "#% increased Trap Damage",
        "#% increased Trap Throwing Speed",
        "#% increased Weapon Critical Strike Chance while Dual Wielding",
        "#% of Physical Attack Damage Leeched as Life",
        "#% of Physical Attack Damage Leeched as Life during Flask effect",
        "#% of Physical Attack Damage Leeched as Mana",
        "#% of Physical Attack Damage Leeched as Mana during Flask effect",
        "#% of Physical Damage taken as Fire Damage",
        "#% reduced Amount Recovered",
        "#% reduced Attribute Requirements",
        "#% reduced Enemy Stun Threshold",
        "#% reduced Fishing Pool Consumption",
        "#% reduced Flask Charges used",
        "#% reduced Mana Cost of Skills",
        "#% reduced Recovery Speed",
        "+# Energy Shield gained for each Enemy hit by your Attacks",
        "+# Extra Charges",
        "+# Life gained for each Enemy hit by Attacks",
        "+# Life gained for each Enemy hit by your Attacks",
        "+# Life gained on Kill",
        "+# Mana gained for each Enemy hit by your Attacks",
        "+# Mana Gained on Kill",
        "+# to Accuracy Rating",
        "+# to all Attributes",
        "+# to Armour",
        "+# to Dexterity",
        "+# to Dexterity and Intelligence",
        "+# to Evasion Rating",
        "+# to Intelligence",
        "+# to Level of Socketed Bow Gems",
        "+# to Level of Socketed Chaos Gems",
        "+# to Level of Socketed Cold Gems",
        "+# to Level of Socketed Fire Gems",
        "+# to Level of Socketed Gems",
        "+# to Level of Socketed Lightning Gems",
        "+# to Level of Socketed Melee Gems",
        "+# to Level of Socketed Minion Gems",
        "+# to Level of Socketed Support Gems",
        "+# to maximum Energy Shield",
        "+# to maximum Life",
        "+# to maximum Mana",
        "+# to Strength",
        "+# to Strength and Dexterity",
        "+# to Strength and Intelligence",
        "+#% Chance to Block",
        "+#% Chance to Block with Shields",
        "+#% to all Elemental Resistances",
        "+#% to Chaos Resistance",
        "+#% to Cold and Lightning Resistances",
        "+#% to Cold Resistance",
        "+#% to Critical Strike Multiplier for Spells",
        "+#% to Critical Strike Multiplier while Dual Wielding",
        "+#% to Critical Strike Multiplier with Cold Skills",
        "+#% to Critical Strike Multiplier with Elemental Skills",
        "+#% to Critical Strike Multiplier with Fire Skills",
        "+#% to Critical Strike Multiplier with Lightning Skills",
        "+#% to Critical Strike Multiplier with One Handed Melee Weapons",
        "+#% to Critical Strike Multiplier with Two Handed Melee Weapons",
        "+#% to Fire and Cold Resistances",
        "+#% to Fire and Lightning Resistances",
        "+#% to Fire Resistance",
        "+#% to Global Critical Strike Multiplier",
        "+#% to Lightning Resistance",
        "+#% to Melee Critical Strike Multiplier",
        "+#% to Quality of Socketed Support Gems",
        "-# to Mana Cost of Skills",
        "100% increased Recovery when on Low Life",
        "135% increased Recovery Speed",
        "33% reduced Recovery Speed",
        "50% increased Amount Recovered",
        "50% increased Recovery Speed",
        "50% of Recovery applied Instantly",
        "60% increased Mana Recovered",
        "Adds #-# Chaos Damage",
        "Adds #-# Cold Damage",
        "Adds #-# Cold Damage to Attacks",
        "Adds #-# Cold Damage to Spells",
        "Adds #-# Fire Damage",
        "Adds #-# Fire Damage to Attacks",
        "Adds #-# Fire Damage to Spells",
        "Adds #-# Lightning Damage",
        "Adds #-# Lightning Damage to Attacks",
        "Adds #-# Lightning Damage to Spells",
        "Adds #-# Physical Damage",
        "Adds #-# Physical Damage to Attacks",
        "Adds Knockback to Melee Attacks during Flask effect",
        "Cannot be Frozen",
        "Causes Bleeding on Hit",
        "Damage Penetrates #% Lightning Resistance",
        "Eternal Iron Hook",
        "Ezomite Shell Hook",
        "Grants #% of Life Recovery to Minions",
        "Hits can't be Evaded",
        "Immunity to Bleeding during Flask effect",
        "Immunity to Curses during Flask effect",
        "Immunity to Freeze and Chill during Flask effect",
        "Immunity to Ignite during Flask effect",
        "Immunity to Shock during Flask effect",
        "Instant Recovery",
        "Instant Recovery when on Low Life",
        "Karui Stone Hook",
        "Minions deal #% increased Damage",
        "Minions have #% Chance to Block",
        "Minions have #% increased maximum Life",
        "Minions have +#% to all Elemental Resistances",
        "Recharges 1 Charge when you deal a Critical Strike",
        "Recharges 3 Charges when you take a Critical Strike",
        "Reflects # Physical Damage to Melee Attackers",
        "Removes 10% of Life Recovered from Mana when used",
        "Removes 15% of Mana Recovered from Life when used",
        "Removes Bleeding on use",
        "Removes Curses on use",
        "Removes Freeze and Chill on use",
        "Removes Shock on use",
        "Totems gain +#% to all Elemental Resistances",
        "Your Flasks grant #% increased Rarity of Items found during flask effect",
        "Your Flasks grant #% increased Rarity of Items found while using a Flask",
        "#% Chance to Block",
        "#% Chance to Block during Flask effect",
        "#% Chance to Block Spells",
        "#% Chance to Block Spells during Flask effect",
        "#% chance to Cast Socketed Lightning Spells on Hit",
        "#% chance to Dodge Spell Damage",
        "#% chance to gain a Frenzy Charge on Kill",
        "#% chance to gain a Power Charge on Kill",
        "#% increased Charges used",
        "#% increased Critical Strike Chance against Blinded Enemies",
        "#% increased Dexterity",
        "#% increased Elemental Damage",
        "#% increased Intelligence",
        "#% increased Physical Damage taken",
        "#% increased Quantity of Items found during Flask effect",
        "#% increased Rarity of Items found during Flask effect",
        "#% increased Strength",
        "#% more Unarmed Physical Damage",
        "#% of Block Chance applied to Spells",
        "#% of Cold Damage Leeched as Life",
        "#% of Fire Damage Leeched as Life",
        "#% of Life Regenerated per Second per Frenzy Charge",
        "#% of Lightning Damage Leeched as Life",
        "#% of Physical Damage Leeched as Life",
        "#% of Physical Damage taken as Lightning Damag",
        "#% reduced Flask effect duration",
        "#% reduced Intelligence",
        "#% reduced maximum Mana",
        "#% reduced Spell Damage",
        "#% reduced Totem Damage",
        "+# Energy Shield gained on Kill"
    ];

}]);